<?php
/**
 * One-time setup: creates the tables and the first admin user, then writes
 * config.php. Refuses to run once config.php exists, so re-uploading the
 * admin folder can never reset an existing install.
 *
 * Only the database and the admin login are required here. Publishing (the
 * GitHub token) is optional and can be connected later from inside the panel.
 */

require_once __DIR__ . '/lib/content.php';
require_once __DIR__ . '/lib/github.php';

function e(?string $v): string { return htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); }

$configFile = __DIR__ . '/config.php';
if (file_exists($configFile)) {
    exit('<p style="font:16px system-ui;padding:2rem">Already installed. <a href="index.php">Go to the admin panel</a>.<br><br>To reinstall, delete <code>config.php</code> on the server first.</p>');
}

$error      = null;
$done       = false;
$publishing = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';
    $email  = strtolower(trim($_POST['email'] ?? ''));
    $name   = trim($_POST['name'] ?? '');
    $pass   = $_POST['password'] ?? '';
    $token  = trim($_POST['gh_token'] ?? '');
    $repo   = trim($_POST['gh_repo'] ?? '');
    $branch = trim($_POST['gh_branch'] ?? '') ?: 'main';

    try {
        if (strlen($pass) < 8) {
            throw new RuntimeException('The admin password must be at least 8 characters.');
        }
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            throw new RuntimeException('Please enter a valid email address.');
        }

        $pdo = new PDO(
            "mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4",
            $dbUser,
            $dbPass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );

        $pdo->exec('CREATE TABLE IF NOT EXISTS admin_users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            email VARCHAR(190) NOT NULL UNIQUE,
            name VARCHAR(120) NOT NULL DEFAULT "",
            password_hash VARCHAR(255) NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_login_at DATETIME NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');

        $stmt = $pdo->prepare('INSERT INTO admin_users (email, name, password_hash) VALUES (?, ?, ?)
                               ON DUPLICATE KEY UPDATE name = VALUES(name), password_hash = VALUES(password_hash)');
        $stmt->execute([$email, $name, password_hash($pass, PASSWORD_DEFAULT)]);

        // Publishing is optional. Only when a token was supplied do we confirm
        // it can actually write before locking the config in.
        if ($token !== '') {
            if ($repo === '') {
                throw new RuntimeException('Enter the repository the token should publish to, or leave the token blank and connect publishing later.');
            }
            [$ghOk, $ghMessage] = gh_check_access($token, $repo);
            if (!$ghOk) {
                throw new RuntimeException($ghMessage);
            }
            $publishing = true;
        }

        $config = "<?php\n// Generated by install.php — keep this file private.\nreturn " . var_export([
            'db' => ['host' => $dbHost, 'name' => $dbName, 'user' => $dbUser, 'pass' => $dbPass],
            'github' => ['token' => $token, 'repo' => $repo, 'branch' => $branch],
        ], true) . ";\n";

        if (file_put_contents($configFile, $config) === false) {
            throw new RuntimeException('Could not write config.php. Give the admin folder write permission (755) and try again.');
        }
        @chmod($configFile, 0640);
        $done = true;
    } catch (Throwable $ex) {
        $error = $ex->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, nofollow">
  <title>Set up DialogHive Admin</title>
  <link rel="stylesheet" href="assets/style.css">
</head>
<body class="login-body">
<?php if ($done): ?>
  <div class="login-card">
    <h1>Setup complete</h1>
    <p class="login-sub">Your admin account is ready. Log in with the email and password you just chose.</p>
    <?php if (!$publishing): ?>
      <p class="login-sub">Publishing is not connected yet, so saves will not reach the live site. Connect it
      any time from <strong>Account → Publishing</strong> inside the panel.</p>
    <?php endif; ?>
    <a class="btn" href="index.php">Go to the admin panel</a>
    <p class="hint" style="margin-top:1rem">For safety, delete <code>install.php</code> from the server now.</p>
  </div>
<?php else: ?>
  <form class="login-card wide" method="post">
    <h1>Set up DialogHive Admin</h1>
    <p class="login-sub">One-time setup. Everything you enter is stored on your own server.</p>

    <?php if ($error): ?><div class="alert bad"><?= e($error) ?></div><?php endif; ?>

    <h2 class="setup-head">1 · Database <span class="hint">— create one in hPanel → Databases → MySQL</span></h2>
    <label>Database host</label>
    <input type="text" name="db_host" value="<?= e($_POST['db_host'] ?? 'localhost') ?>" required>
    <label>Database name</label>
    <input type="text" name="db_name" value="<?= e($_POST['db_name'] ?? '') ?>" required placeholder="u504688092_dialoghive">
    <label>Database user</label>
    <input type="text" name="db_user" value="<?= e($_POST['db_user'] ?? '') ?>" required placeholder="u504688092_admin">
    <label>Database password</label>
    <input type="password" name="db_pass" required>

    <h2 class="setup-head">2 · Your admin login</h2>
    <label>Your name</label>
    <input type="text" name="name" value="<?= e($_POST['name'] ?? '') ?>" placeholder="Usman">
    <label>Email <span class="hint">— you will log in with this</span></label>
    <input type="email" name="email" value="<?= e($_POST['email'] ?? '') ?>" required>
    <label>Password <span class="hint">— at least 8 characters</span></label>
    <input type="password" name="password" required>

    <details class="setup-optional"<?= !empty($_POST['gh_token']) ? ' open' : '' ?>>
      <summary><span class="setup-head">3 · Publishing <span class="hint">— optional, you can do this later</span></span></summary>
      <p class="hint">Skip this to finish setup now. Until publishing is connected the panel works normally,
      but saves will not reach the live site. You can connect it any time from <strong>Account → Publishing</strong>.</p>
      <label>GitHub token</label>
      <input type="password" name="gh_token" placeholder="ghp_…" autocomplete="off">
      <p class="hint">Create at github.com/settings/tokens/new with the <strong>repo</strong> scope. Entered once, stored on your server — you will never need it again.</p>
      <label>Repository</label>
      <input type="text" name="gh_repo" value="<?= e($_POST['gh_repo'] ?? 'devgroup06/chatbot-agency-website') ?>">
      <label>Branch</label>
      <input type="text" name="gh_branch" value="<?= e($_POST['gh_branch'] ?? 'main') ?>">
    </details>

    <button type="submit">Finish setup</button>
  </form>
<?php endif; ?>
</body>
</html>
