<?php
/**
 * Database connection (PDO). Credentials come from config.php, which the
 * installer writes on the server and which is deliberately not in git.
 */

function config_file(): string
{
    return __DIR__ . '/../config.php';
}

/**
 * Reads config.php. Passing $replace swaps the cached copy in memory, which
 * save_config() uses after rewriting the file.
 */
function config(?array $replace = null): array
{
    static $config = null;

    if ($replace !== null) {
        return $config = $replace;
    }

    if ($config === null) {
        $file = config_file();
        if (!file_exists($file)) {
            header('Location: install.php');
            exit;
        }
        $config = require $file;
    }
    return $config;
}

/** Rewrites config.php. Returns [ok, message]. */
function save_config(array $config): array
{
    $php = "<?php\n// Generated by the DialogHive admin panel — keep this file private.\nreturn "
        . var_export($config, true) . ";\n";

    if (file_put_contents(config_file(), $php) === false) {
        return [false, 'Could not write config.php. Give the admin folder write permission (755) and try again.'];
    }
    @chmod(config_file(), 0640);
    config($config);
    return [true, 'Saved.'];
}

function db(): PDO
{
    static $pdo = null;
    if ($pdo === null) {
        $c = config()['db'];
        $dsn = "mysql:host={$c['host']};dbname={$c['name']};charset=utf8mb4";
        $pdo = new PDO($dsn, $c['user'], $c['pass'], [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ]);
    }
    return $pdo;
}
